import type { Metadata } from "next";
import {Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ThemeProvider } from "@/context/themeContext";

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Next News Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <ThemeProvider>
            <Navbar/>
            <main className="min-h-screen max-w-7xl mx-auto  px-4 sm:px-6 lg:px-8">
                {children}
            </main>
            <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
